### ISSUE TITLE
In shining the holy ark the ground is partially missing & battle music is choppy

### ISSUE THREAD

**Issue by falcon2991** [StrikerX3/Ymir#287]
This is the PAL version:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/90473de7-3605-4945-8b22-83f71b7f2842" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/aba21d21-dcb8-4195-b548-34777e6aab9e" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/053dc34c-3a1c-4872-8132-68291b30eda3" />

The ground partially vanishes during scenes when feet should be visible.

**Comment by AydanWatkins** [comment]
Don't quote me on this, but the 'missing' bits at the bottom seem like the black pal borders as they also show up the top... not all games have them on Ymir but some do such as Deep Fear.

**Comment by AydanWatkins** [comment]
graphical issues with the blue bars are fixed as of dev build - ymir-sdl3-0.1.6-dev-2025-07-12

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/0515a6e2-5ce4-4852-8076-951e9d0edc11" />

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/81dbcf54-0701-4ef1-b009-bba27f22730c" />

-
-
-

**However the audio issues with battle music etc remain**. There is also a sprite during the intro scene behind the 3 main party characters which is glitched, it looks like it's supposed to be a rock but has visible lines like each row is not aligning correctly to form the sprite...

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/5fef1c76-14fd-44a1-a7de-cc6908bd9fe7" />

**Comment by thelastangryman1907** [comment]
As of the latest nightly the rock is still broken, battle music still plays at the wrong speed randomly slowing down and speeding up, and the game runs way too fast. Movement and menu animations are all in fast forward.

**Comment by AydanWatkins** [comment]
sprite issues fixed in newest nightly: 0.1.8+7ae3604b-dev

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/29c33b25-a333-4c1a-b499-7887957f9fa4" />

music is also fixed now.

issue can be closed

**Comment by thelastangryman1907** [comment]
@AydanWatkins Does it still run too fast? try walking around and look at the menu animations.

**Comment by saifulgazipur220-lang** [comment]
ymir emulator shining the holy ark all Nothing - 0%

<img width="1364" height="768" alt="Image" src="https://github.com/user-attachments/assets/b824d06d-044b-4255-b88d-dfd173acb87b" />

**Comment by thelastangryman1907** [comment]
@saifulgazipur220-lang Sorry?

**Comment by AydanWatkins** [comment]
Bugs reported on this issue have all been fixed.

Only remaining issue right now (without playing through the whole game) - is that it seems to read controller inputs twice the speed or like, double input for a single one if that makes sense? Best example if if you press left or right once to turn, you do a full 180 vs just turning 90 degrees.

Might be worth updating the title of this ticket to reflect that. But playing through the intro seems fine outside of that.

**Comment by thelastangryman1907** [comment]
@AydanWatkins It's something to do with animations running too fast. If you pause you can see the menu icons are going too fast as well. It's the same problem as Welcome House (Japan)

**Comment by saifulgazipur220-lang** [comment]
ymir emulator shining the holy ark all file animations running @StrikerX3 @AydanWatkins @falcon2991 @thelastangryman1907

**Comment by AydanWatkins** [comment]
<img width="1079" height="852" alt="Image" src="https://github.com/user-attachments/assets/9fa665aa-f994-4654-a383-917a3f2f22ba" />

speed issue with animations being too fast and double inputs are FIXED as of this current test build!!!

**Comment by AydanWatkins** [comment]
Not aware of any further issues in this current ticket, can be closed when ready

**Comment by thelastangryman1907** [comment]
Movement speed seems to work correctly now. One push of the D pad moves you one space as it should.

**Comment by StrikerX3** [comment]
All reported issues are resolved. Closing.
