### ISSUE TITLE
Dark Seed II (Japan) - FMVs, menus and in-game graphics are all broken

### ISSUE THREAD

**Issue by thelastangryman1907** [StrikerX3/Ymir#316]
FMVs in the game all run in slow motion, are broken and will freeze if you let them play. But can be skipped. 

<img width="1903" height="1012" alt="Image" src="https://github.com/user-attachments/assets/319cff1b-92fa-4e73-840f-3de53b247e86" />

The main menu is also broken.

<img width="1918" height="1015" alt="Image" src="https://github.com/user-attachments/assets/442422e5-29d7-4030-a3ba-898cc0027e9a" />

So are the graphics in game.

<img width="1918" height="1012" alt="Image" src="https://github.com/user-attachments/assets/589652af-32a8-4974-a7a1-d96ec2676ddc" />

**Comment by StrikerX3** [comment]
I think the game is trying to change the VDP1 command table while the chip is drawing a frame? Whatever the case, it seems to be seriously abusing the VDP1 to the point where the emulator is struggling to run even on my beefy CPU: 72% speed in turbo mode at the intro FMV.

Needs further investigation.

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/b76bd496-949c-4218-9d98-12f618d63694" />

**Comment by StrikerX3** [comment]
Severe slowdown fixed by a variety of VDP1 optimizations, especially the stopgap cycle counting in c3347d4c8e12a4d3978def362a6b9ba862e31d02.

**Comment by StrikerX3** [comment]
Slowdown fix included in [0.1.8](https://github.com/StrikerX3/Ymir/releases/tag/v0.1.8).

**Comment by thelastangryman1907** [comment]
FMVs and menus are all still broken but SH2 mostly fixes the in-game sprites. They only flicker occasionally 

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/8512be7a-29e5-4339-9c90-bdf680280465" />
