### ISSUE TITLE
NiGHTS Into Dreams doesn't play the intro video

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/Ymir#46]
I haven't researched the reason for this yet, but the game works fine if you smash the Start button to get past the non-working intro video.

**Comment by StrikerX3** [comment]
Fixed in 8a946294de40717c143bbfb006db743bc8463512

The games uses a special CD Block filter configuration to split data from the movie file into two tracks. See the writeup [here](https://github.com/StrikerX3/Ymir/blob/main/docs/dev-notes/finicky-games/cdblock-nontrivial-filters.txt).

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/bbc5d80c-7b48-4d11-a57b-de6de6da8971" />

<img width="493" height="534" alt="Image" src="https://github.com/user-attachments/assets/b6295d19-b33d-474c-b898-074a6f8d4f57" />

**Comment by StrikerX3** [comment]
Fix included in [0.1.7](https://github.com/StrikerX3/Ymir/releases/tag/v0.1.7).

**Comment by markkrauth** [comment]
I'm probably a total noob and missing something, but I still cannot get the intro video of Nights to play on ymir-windows-x86_64-AVX2-v0.2.0.

## Enhancements
### Video
- [x] Deinterlace
- [ ] Transparent meshes
## Accuracy settings
### System
- [x] Emulate SH-2 cache
### Video
- [x] Threaded VDP2 rendering
  - [x] Use dedicated thread for deinterlaced rendering
  - [ ] Include VDP1 rendering in VDP2 renderer thread
### Audio
- Interpolation mode: Linear
- Emulation step granularity: 1 slot
### CD Block
- [x] Use low level CD Block emulation
- CD read speed: 2x

Can anybody help please?

**Comment by StrikerX3** [comment]
Not sure what's going on there. I replicated your settings, tested enabling and disabling the SH-2 cache and CD Block LLE, and even tried CHD vs. BIN/CUE and I always get the video playing back without issues no matter what combination I use. This was tested on a fresh install of the 0.2.0 release.

**Comment by markkrauth** [comment]
Thanks for helping to look into it. I fixed it. I got a different version of the game's ROM and that worked without issues.

**Comment by The-Dreamfinder** [comment]
> Thanks for helping to look into it. I fixed it. I got a different version of the game's ROM and that worked without issues.

I have the same issue and still can't figure it out. Tried re-acquiring the files too, same exact issue. Videos works fine with Retroarch cores.
