### ISSUE TITLE
Sol Divide (Japan) - Doesn't boot

### ISSUE THREAD

**Issue by thelastangryman1907** [StrikerX3/Ymir#470]
No dice

<img width="1280" height="896" alt="Image" src="https://github.com/user-attachments/assets/71aea3b7-b1ca-452d-b805-83cfe28bfe3d" />

**Comment by thelastangryman1907** [comment]
With LLE CD Block the game now makes it partway into the opening FMV before freezing with corrupted graphics. Without LLE it still doesn't boot.

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/563a1f53-58e2-443b-b220-dbf43ac6d2bb" />

**Comment by StrikerX3** [comment]
Fixed somewhere between 44958a15eae79fd893874e62ef006b3bdd33e567 and b334bedb1d635307d6288b2cd3f032f5eebb04a8

**Comment by thelastangryman1907** [comment]
Game works fine with LLE except for occasional black garbage lines during the opening FMV that don't happen in Mednafen. Still doesn't boot with HLE. 

<img width="1280" height="960" alt="Image" src="https://github.com/user-attachments/assets/23c46e87-4990-465f-9334-12083239f0fd" />

**Comment by thelastangryman1907** [comment]
No change as of Ymir 0.3.2-dev+241c3893
