### ISSUE TITLE
WarCraft II - The Dark Saga (Europe) (En,Fr,De,Es,It) - Graphical garbage after starting a new campaign

### ISSUE THREAD

**Issue by thelastangryman1907** [StrikerX3/Ymir#471]
After the loading screen when you start a new campaign this shows up on screen for a few seconds.

<img width="1918" height="1015" alt="Image" src="https://github.com/user-attachments/assets/2a295acf-4b45-493e-9b1f-eedd7748c6f6" />

**Comment by StrikerX3** [comment]
This is caused by the SH2 running too fast. The issue will be resolved when rough bus timings are implemented.

While fading out, the MSH2 runs a tight loop at 604B640-604B6B8 which copies data into VDP2 VRAM in the area used by NBG1 which is filled with blank tiles. The CPU runs fast enough to the point where it manages to overwrite those tiles while the display is not yet fully faded out. Slowing down uncached memory accesses by a factor of 20 fixes the problem, but results in the CPU running too slow.

**Comment by thelastangryman1907** [comment]
Still happens even with SH2 + LLE

**Comment by AydanWatkins** [comment]
<img width="1095" height="872" alt="Image" src="https://github.com/user-attachments/assets/1ac2bd45-0fcf-4b28-b5cb-3cfeeacb1fc2" />

fixed as of newest nightly build using HLE.

**Comment by thelastangryman1907** [comment]
Still happens. 

<img width="1408" height="960" alt="Image" src="https://github.com/user-attachments/assets/824050b2-8816-43d2-a148-cefdddd8a014" />
