### ISSUE TITLE
Gremlin Interactive Demo Disc (Europe) - Demo for Hardcore 4x4 freezes before getting to gameplay

### ISSUE THREAD

**Issue by thelastangryman1907** [StrikerX3/Ymir#539]
It never gets past this screen. The full version works fine though so it's just this particular demo that's broken.

<img width="1408" height="1024" alt="Image" src="https://github.com/user-attachments/assets/2c958320-c1f0-40df-abfc-7e0a159fa411" />

The demo on the disc for Actua Soccer Club Edition also freezes but the full game also has that problem so it's not surprising. 

<img width="1408" height="960" alt="Image" src="https://github.com/user-attachments/assets/82065fdf-5281-4d4e-a01c-ab092834ad27" />

**Comment by StrikerX3** [comment]
Fixed in 494085d05ca70e9120d02925bc96271a6fe3d7b2 by partially undoing the CD Block state transition delays.

**Comment by thelastangryman1907** [comment]
Still doesn't work even with LLE CD Block.

**Comment by arklord13** [comment]
the Hardcore 4x4 bug is still happening in 0.3.2-dev+36ce9269 but can be "solved" by disabling "threaded vdp1 renderer"
