### ISSUE TITLE
Burning Rangers, flickering when saving someone, ymir 0.2.1-dev+6fc35682

### ISSUE THREAD

**Issue by rollingstart222** [StrikerX3/Ymir#704]
Hi there, I am using the latest nightly build as of today (November 12th) and noticed this issue while playing the first level of Burning Rangers: 

<img width="1225" height="971" alt="Image" src="https://github.com/user-attachments/assets/35f39d1c-cf87-4890-ac47-fd0ba4339984" />

As you can see, some text isn't visible, because it was flickering during the screenshot. This seems to happen everytime you save someone in the game. It's a minor issue, but thought I would bring it to your attention. I can confirm as I used to have this game back in the day, that the text doesn't flicker. I'm using the USA version of BR. 

Thank you so much for making this incredible emulator!!

**Comment by StrikerX3** [comment]
Issue alleviated in 6d204bc5ebf58c4fa9ba41c72e2a77468f96b127. The text is now fully drawn, but the top portion is occasionally erased.

**Comment by StrikerX3** [comment]
Needs slightly faster VDP1 processing to fully fix the issue (`m_VDP1CyclesShift = 3`). Improved VDP1 timing accuracy should fix this.

Temporary fix included in [0.3.0](https://github.com/StrikerX3/Ymir/releases/tag/v0.3.0).

**Comment by thelastangryman1907** [comment]
This is still broken.

<img width="1408" height="896" alt="Image" src="https://github.com/user-attachments/assets/4a179dc9-4803-4c60-aa8b-8885c69de7ad" />

Here's a save state to make future testing easier.

[branger.zip](https://github.com/user-attachments/files/27483398/branger.zip)

**Comment by AydanWatkins** [comment]
still broken as of latest nightly ymir 0.3.2+dev5c0b3c24 , the top lines of text (transfer complete) and the survivors name flicker still. hopefully a simple fix to also tick this one off the list
