### ISSUE TITLE
resident evil lockup

### ISSUE THREAD

**Issue by tofubotu** [StrikerX3/Ymir#710]
### Video
- [x] Deinterlace
- [x] Transparent meshes
### System
- [ ] Emulate SH-2 cache
### Video
- [x] Threaded VDP2 rendering
  - [x] Use dedicated thread for deinterlaced rendering
  - [ ] Include VDP1 rendering in VDP2 renderer thread
### Audio
- Interpolation mode: Linear
- Emulation step granularity: 1 slot
### CD Block
- [ ] Use low level CD Block emulation
- CD read speed: 2x
Disc hash: 2C8D07B0BEBCCD60C5997AA040B315E7

Right after returning from Battle Mode to normal game it locks up. Dump is good, works on Bizhawk.
I tried various settings but end result is same. Happy to help solve this in anyway I can.

I love this emulator, its way more responsive than anything else and I really like RE1 Battle Mode!
Using this now for this mini game for sure. Will test if i can reach to end.

<img width="1252" height="849" alt="Image" src="https://github.com/user-attachments/assets/9f9c0181-3e27-4935-9274-d62a57df1e1c" />

**Comment by StrikerX3** [comment]
Try using LLE CD Block emulation, see if that fixes the hangs.

**Comment by tofubotu** [comment]
Tested, with all of them, hard resets

<img width="911" height="512" alt="Image" src="https://github.com/user-attachments/assets/5456e24a-d2ae-4094-97bc-be2c7ddfd777" />

Last one i tested with 105, and i tried to skip the intro video, it went black and then I got this error

<img width="730" height="337" alt="Image" src="https://github.com/user-attachments/assets/a288c0fb-b196-40eb-a253-62bfc51b6a1b" />

**Comment by StrikerX3** [comment]
Interesting. Try the latest nightly build, perhaps the crash has been fixed already.

**Comment by tofubotu** [comment]
Tested, same thing happens with nightly too

**Comment by arklord13** [comment]
still happening in 0.3.0-dev+77c228ce, sh-2 doesnt help either !

**Comment by AydanWatkins** [comment]
been playing with newest nightly build using HLE - voices work fine, fmvs fine, all seems to be quite playable. got through all intro cutscenes and to the save room with rebecca with no issues. might be worth closing this particular ticket now.

<img width="1227" height="972" alt="Image" src="https://github.com/user-attachments/assets/f536ae1a-5729-4029-af2f-1631bf9a2797" />

**Comment by thelastangryman1907** [comment]
Battle mode still freezes after you quit back to the main menu. Start a new game, make a save, restart the emulator and load this save state. 

[battle.zip](https://github.com/user-attachments/files/29303524/battle.zip)
