### ISSUE TITLE
[Bug] Sonic Jam's Genesis emulation has graphical and audio issues

### ISSUE THREAD

**Issue by DavidHolandaOne** [StrikerX3/Ymir#83]
The Sonic's Genesis games on Sonic Jam have a graphic error in-game, with vertical line parts being misplaced.
![Image](https://github.com/user-attachments/assets/705fa0e8-fbad-4f7e-bef6-b0e6dd763a77)
![Image](https://github.com/user-attachments/assets/f13a0c73-b894-4ccd-a983-e24466e793b2)
![Image](https://github.com/user-attachments/assets/c22ec5ac-9ead-42e5-b97d-5b7f8b295a65)
![Image](https://github.com/user-attachments/assets/988a67ce-ac2f-4138-bd1c-a6002d975fa1)
![Image](https://github.com/user-attachments/assets/6e636bc2-ba46-443b-a594-ef9f1e472075)

In top of that, the background music also disappear after some seconds and only the SFX remains.
And playing Sonic the Hedgehog 3 without the "Sonic & Knuckles" lock-in addon causes the game to crash.

Sonic World runs well at least. However the Sound Test has the same audio issue when playing the Genesis music, making the whole music be silent especially in Sonic World.

**Comment by StrikerX3** [comment]
Some of the recent fixes to graphics bugs seem to have improved graphics on this game, though there are still a few bugs remaining.

![Image](https://github.com/user-attachments/assets/a848701f-e9fc-4ae8-bbd5-403a31511a76)

![Image](https://github.com/user-attachments/assets/0409d270-d7e4-4275-af77-745c02ccf79b)

![Image](https://github.com/user-attachments/assets/0efd2603-9342-40e5-8b60-738ecb41e5cd)

![Image](https://github.com/user-attachments/assets/799161c0-9615-4011-bc33-65265a20eae5)

**Comment by AydanWatkins** [comment]
@StrikerX3 my sincere apologies on the duplicate post. I'm still learning my way around github :)

as mentioned above, the background music also disappear after some seconds and only the SFX remains.

**Comment by StrikerX3** [comment]
No worries! I'm just making sure the issues are organized.

You can use the search bar to find for existing issues:

![Image](https://github.com/user-attachments/assets/f01d32bc-61ca-4d81-89ae-973810374c53)

Here's the original reported issue:

> When playing the SONIC WORLD section of Sonic Jam, there is a weird graphical glitch where it renders this line (circles in red):
>
> ![Image](https://github.com/user-attachments/assets/17122cc4-ac9b-4da0-acd9-cb3f68093cd0)
> 
> When the intro movie finishes or is skipped, the PRESS START and game mode select text is missing:
> 
> ![Image](https://github.com/user-attachments/assets/56548bbe-9bb1-4e2e-ab2c-fbe32cb8e5e0)
> 
> How it SHOULD look:
> 
> ![Image](https://github.com/user-attachments/assets/7e4574d6-7efa-49dd-b37c-c37baf8355cf)
> 
> Graphics glitches in the games such as Sonic 1:
> 
> ![Image](https://github.com/user-attachments/assets/9321794d-2fd0-4b1b-abcb-579bc255f2bb)
> 
> Same in Sonic 2, same looking glitch so likely all linked..
> 
> ![Image](https://github.com/user-attachments/assets/b3a85910-744e-470f-bca9-3074afc7b351)
> 
> Lastly, when you pickup a ring or after a few seconds the music of the levels (Sonic 1, 2 etc) just stops.

**Comment by markkrauth** [comment]
It's hard to make a screenshot of this, but another thing I noticed is that menu texts for each of the classic games ('game start', 'extra game', etc.) start glitching after being selected, while the 'loading' prompt appears. (The text stutters and flickers).

**Comment by StrikerX3** [comment]
> It's hard to make a screenshot of this, but another thing I noticed is that menu texts for each of the classic games ('game start', 'extra game', etc.) start glitching after being selected, while the 'loading' prompt appears. (The text stutters and flickers).

Does this happen with threaded VDP enabled or disabled? Does it change depending on this option?

I'm starting to suspect that I might have to move VDP1 rendering to the emulator thread or at least add more sync points to it.

**Comment by markkrauth** [comment]
> > It's hard to make a screenshot of this, but another thing I noticed is that menu texts for each of the classic games ('game start', 'extra game', etc.) start glitching after being selected, while the 'loading' prompt appears. (The text stutters and flickers).
> 
> Does this happen with threaded VDP enabled or disabled? Does it change depending on this option?
> 
> I'm starting to suspect that I might have to move VDP1 rendering to the emulator thread or at least add more sync points to it.

Just tested it. This happens with VDP either being enabled, as well as disabled.

**Comment by StrikerX3** [comment]
Ok, it's something else unrelated to threading then. Thanks for confirming that!

**Comment by AydanWatkins** [comment]
https://github.com/user-attachments/assets/0571644d-6c21-4cfa-9729-3ebc1bb1f06f

MAJOR graphical improvements now in the games, no more skybox/background issues. However the audio issue still persists.

**Comment by AydanWatkins** [comment]
Music has been fixed as of newest dev builds! Only remaining issue now is when using powerups such as invincibility or speed shoes, the music stops playing about 2 seconds or so before it should and the normal level music comes back in.

**Comment by AydanWatkins** [comment]
also one final graphical issue in sonic world section, when bouncing on a spring, the vdp2 layer on the sky seems to get a weird glitch..

https://github.com/user-attachments/assets/1520456f-2900-41ea-ba70-4095ccaabd38

**Comment by StrikerX3** [comment]
Fixes included in [0.1.7](https://github.com/StrikerX3/Ymir/releases/tag/v0.1.7). The sky bug still isn't fixed.

**Comment by AydanWatkins** [comment]
the invincibility power up music ending and going quiet about 2/3 seconds before it should is also not fixed yet, only that and the sky remain from what I've tested! :)

**Comment by StrikerX3** [comment]
Jotting this down so that I don't forget: the skybox issue is related to line color data on rotation parameters. Check addressing, values, etc.

**Comment by StrikerX3** [comment]
Fixed in 4d0a3eafc84abf2e8584b55ac946348bd0d38f8a

**Comment by AydanWatkins** [comment]
Awesome stuff, just some audio related issues now it would seem as mentioned in my post about invincibility music ending before it should etc.

**Comment by AydanWatkins** [comment]
Okay, odd bug, if you play through a level, the music plays fine at around a minute or so in, you get distorted noise and then the music stops. Just audio issues remaining with Jam.

**Comment by StrikerX3** [comment]
Skybox fix included in [0.1.8](https://github.com/StrikerX3/Ymir/releases/tag/v0.1.8).

**Comment by keat16** [comment]
I played through all of Sonic 1 and didn't encounter any sound glitches with LLE CD Block.

**Comment by AydanWatkins** [comment]
Yup can confirm LLE Cdblock fixes the audio distortion issues AND the invincibility music looping correctly etc. I think this ticket is pretty much closable unless someone else has come across another issue? But all reported on here seem to be done.

**Comment by StrikerX3** [comment]
Seems like the issues have been solved or can be worked around with LLE CD Block. Closing.

**Comment by StrikerX3** [comment]
HLE CD Block fixes included in [v0.3.2](https://github.com/StrikerX3/Ymir/releases/tag/v0.3.2).
